### ISSUE TITLE
Ecoregion Level 2

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1512]
The Ecoregion Level 2 information returned is not grabbing from the correct column in the shapefile/dbf

![Screenshot_2019-08-06 FBIS Map(9)](https://user-images.githubusercontent.com/45286876/62526236-27aff380-b839-11e9-987c-e95f0bd90e47.png)

It should be LEVEL column, not LEV2 column
![image](https://user-images.githubusercontent.com/45286876/62526389-73fb3380-b839-11e9-855a-3b3a67d7e19b.png)

**Comment by dimasciput** [comment]
@helendallas which site is this?

**Comment by dimasciput** [comment]
@NyakudyaA can you fix this?

**Comment by helendallas** [comment]
All sites

**Comment by NyakudyaA** [comment]
@dimasciput I have fixed this in Geoserver. You can fetch it again

**Comment by dimasciput** [comment]
re-fetching it now in the production server

**Comment by helendallas** [comment]
Checked this and it still shows the old numbers. Checked on live and testing site.
![Uploading Screenshot_2019-08-15 FBIS Map(1).png…]()

**Comment by NyakudyaA** [comment]
@dimasciput  Can you update the sites with new values from Geocontext
![eco-region](https://user-images.githubusercontent.com/2510900/64342672-4eee1200-cfeb-11e9-9366-321300201fd0.png)
