### ISSUE TITLE
Biobase data - Please check all data has been migrated

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1887]
@dimasciput 
It is very hard to check that all the Biobase data has been migrated accurately and entirely. I have thus done a random check.

Noted the following:  For JCW02
Only one taxon is reported, with 21 occurrences. This is incorrect

Original data has: 9 taxa with 99 occurrences.
screenshot and excel sheet (from Biobase) here.

![Screenshot_2020-01-31 FBIS Map(8)](https://user-images.githubusercontent.com/45286876/73544410-c791b700-4441-11ea-9fe5-951cbb417f11.png)

Original data extracted from Biobase
[JCW02.xlsx](https://github.com/kartoza/django-bims/files/4139674/JCW02.xlsx)

**Comment by helendallas** [comment]
Another example : Sites   and reference correct, data missing

O'Keeffe   J.H. | 1990 | KUB01
O'Keeffe J.H. | 1990 | KUB02
O'Keeffe J.H. | 1990 | KUB03
O'Keeffe J.H. | 1990 | KUB04
O'Keeffe J.H. | 1990 | KUB05

Original data extracted from Biobase
[OKeeffe 1990 Kubusi.xlsx](https://github.com/kartoza/django-bims/files/4146645/OKeeffe.1990.Kubusi.xlsx)

**Comment by dimasciput** [comment]
@helendallas can you try again? I updated source collection of all biobase data to fbis.

**Comment by helendallas** [comment]
@dimasciput 
I am trying to check . Now there are more records on FBIS compared to the data extracted from Biobase, but I need to verify that this is not a biotope issue.  

The CSV file is missing Biotope fields:
Broad Biotope, Specific Biotope, Substratum.   

PLease can you follow up as I am sure this was captured in an earlier ticket.

I will revert soonest

**Comment by helendallas** [comment]
@dimasciput 
It is really difficult to check. It seems that the sites are all coming through now - I have checked a subset; but duplicate occurrence records are coming through, and then some taxa that don't appear to be in the original paper.  I am not able to recreate the Biobase data accurately so am relying on trawling through the original papers, which is challenging.  

See the attached study:
Coetzer 1986 Bree01

Red show correct records, black are duplicates, yellow were not in the original study as far as I can tell.
[Coetzer 1986 From FBIS.xlsx](https://github.com/kartoza/django-bims/files/4151984/Coetzer.1986.From.FBIS.xlsx)

Please can you check .

**Comment by dimasciput** [comment]
ok @helendallas , I will remove the duplicates, I don't know why it's there, strange. Thanks for the report.

**Comment by helendallas** [comment]
@dimasciput Please update me on this ticket.

**Comment by dimasciput** [comment]
@helendallas the duplicated data has been removed, please try it again.

**Comment by helendallas** [comment]
Please see 50 occurrences listed on left, but 44 on overview panel.
![Screenshot_2020-02-17 FBIS Map](https://user-images.githubusercontent.com/45286876/74640551-658ebc80-5178-11ea-9589-e28c50d84a0d.png)

Then a much bigger issue is the data: It is not correct. I have only rechecked this one site. 
The data returned for this site is not correct. 
There should be 24 taxa for Bree01 on the 1975.03.  Please see attached scanned document of the original reference plus the excel data extracted from Biobase. 
The taxa listed include several that were recorded in the study but not at the site.. Only those taxa where Presence = 1, and in this study, there was also an abundance value should be listed at this site. I suspect all taxa have been pulled in regardless of if they were at the site or not, which is incorrect.
[Coetzer 1986 Bree01 from Biobase.xlsx](https://github.com/kartoza/django-bims/files/4213026/Coetzer.1986.Bree01.from.Biobase.xlsx)

[Coetzer 1986 Invertebrate data table Original.pdf](https://github.com/kartoza/django-bims/files/4213028/Coetzer.1986.Invertebrate.data.table.Original.pdf)

**Comment by dimasciput** [comment]
@helendallas @jeremyshelton @timlinux 

After investigating from the rivers db, actually there are 52 occurrences with different taxon names : 

SiteCode|BioDate|Abundance|Taxon                    |
--------|-------|---------|-------------------------|
BREE01  |1975.03|         |Adenophlebia sp.         |
BREE01  |1975.03|         |Aeschna sp.              |
BREE01  |1975.03|         |Afronurus sp.            |
BREE01  |1975.03|   7.4000|Ancylidae                |
BREE01  |1975.03|  33.1000|Annelida                 |
BREE01  |1975.03|   0.2000|Aulonogyrus sp.          |
BREE01  |1975.03|         |Baetis bellus            |
BREE01  |1975.03|   1.9000|Baetis harrisoni         |
BREE01  |1975.03|         |Baetis latus             |
BREE01  |1975.03|   0.9000|Caenidae                 |
BREE01  |1975.03|         |Centroptilum crassi      |
BREE01  |1975.03|   1.3000|Centroptilum excisum     |
BREE01  |1975.03|   1.3000|Centroptilum medium      |
BREE01  |1975.03|         |Centroptilum varium      |
BREE01  |1975.03|   0.2000|Ceratopogonidae          |
BREE01  |1975.03|   8.1000|Cheumatopsyche afra      |
BREE01  |1975.03|         |Cheumatopsyche thomasseti|
BREE01  |1975.03|   0.6000|Chironomini              |
BREE01  |1975.03|   0.1000|Cloeon africanum         |
BREE01  |1975.03|         |Cloeon virgiliae         |
BREE01  |1975.03|   1.3000|Cypridopsis sp.          |
BREE01  |1975.03|         |Diptera spp.             |
BREE01  |1975.03|         |Dryopidae                |
BREE01  |1975.03|         |Ecnomus sp.              |
BREE01  |1975.03|         |Eruciform larvae         |
BREE01  |1975.03|   0.1000|Gastropoda               |
BREE01  |1975.03|         |Helothemis sp.           |
BREE01  |1975.03|   1.5000|Hemiptera                |
BREE01  |1975.03|         |Hydra sp.                |
BREE01  |1975.03|   0.1000|Hydraenidae              |
BREE01  |1975.03|   0.1000|Hydracarina              |
BREE01  |1975.03|   0.1000|Hydrophilidae            |
BREE01  |1975.03|         |Hydroptila sp.           |
BREE01  |1975.03|         |Macronema capense        |
BREE01  |1975.03|         |Macrostemum capense      |
BREE01  |1975.03|   0.8000|Nematoda                 |
BREE01  |1975.03|         |Neurocaenis discolor     |
BREE01  |1975.03|         |Orectogyrus sp.          |
BREE01  |1975.03|   9.1000|Orthocladiinae           |
BREE01  |1975.03|         |Orthotrichia sp.         |
BREE01  |1975.03|   0.6000|Ostracoda                |
BREE01  |1975.03|         |Oxyethira sp.            |
BREE01  |1975.03|         |Pelecypoda               |
BREE01  |1975.03|         |Plecoptera               |
BREE01  |1975.03|         |Pseudocloeon maculosum   |
BREE01  |1975.03|  27.4000|Simuliidae               |
BREE01  |1975.03|         |Sympetrum sp.            |
BREE01  |1975.03|   1.9000|Tanypodinae              |
BREE01  |1975.03|   0.5000|Tanytarsini              |
BREE01  |1975.03|         |Trichoptera (larvae)     |
BREE01  |1975.03|         |Trithemis sp.            |
BREE01  |1975.03|   1.4000|Turbellaria              |

**Comment by dimasciput** [comment]
And this is from the fbis site : 

SiteCode|BioDate|Abundance|Taxon                    |
--------|-------|---------|-------------------------|
| BREE01 | 1975-03-01 | None | Adenophlebia sp. |
| BREE01 | 1975-03-01 | None | Aeschna sp. |
| BREE01 | 1975-03-01 | None | Afronurus sp. |
| BREE01 | 1975-03-01 | 7.4 | Ancylidae |
| BREE01 | 1975-03-01 | 33.1 | Annelida |
| BREE01 | 1975-03-01 | 0.2 | Aulonogyrus sp. |
| BREE01 | 1975-03-01 | None | Baetis bellus |
| BREE01 | 1975-03-01 | 1.9 | Baetis harrisoni |
| BREE01 | 1975-03-01 | 0.9 | Caenidae |
| BREE01 | 1975-03-01 | None | Centroptilum crassi |
| BREE01 | 1975-03-01 | 1.3 | Centroptilum excisum |
| BREE01 | 1975-03-01 | 0.2 | Ceratopogonidae |
| BREE01 | 1975-03-01 | 8.1 | Cheumatopsyche afra |
| BREE01 | 1975-03-01 | None | Cheumatopsyche thomasseti |
| BREE01 | 1975-03-01 | 0.6 | Chironomini |
| BREE01 | 1975-03-01 | 0.1 | Cloeon africanum |
| BREE01 | 1975-03-01 | None | Cloeon virgiliae |
| BREE01 | 1975-03-01 | 1.3 | Cypridopsis sp. |
| BREE01 | 1975-03-01 | None | Diptera spp. |
| BREE01 | 1975-03-01 | None | Dryopidae |
| BREE01 | 1975-03-01 | None | Ecnomus sp. |
| BREE01 | 1975-03-01 | None | Eruciform larvae |
| BREE01 | 1975-03-01 | 0.1 | Gastropoda |
| BREE01 | 1975-03-01 | None | Helothemis sp. |
| BREE01 | 1975-03-01 | 1.5 | Hemiptera |
| BREE01 | 1975-03-01 | None | Hydra sp. |
| BREE01 | 1975-03-01 | 0.1 | Hydracarina |
| BREE01 | 1975-03-01 | 0.1 | Hydraenidae |
| BREE01 | 1975-03-01 | 0.1 | Hydrophilidae |
| BREE01 | 1975-03-01 | None | Hydroptila sp. |
| BREE01 | 1975-03-01 | None | Macronema capense |
| BREE01 | 1975-03-01 | None | Macrostemum capense |
| BREE01 | 1975-03-01 | 0.8 | Nematoda |
| BREE01 | 1975-03-01 | 0.8 | Nematoda |
| BREE01 | 1975-03-01 | None | Neurocaenis discolor |
| BREE01 | 1975-03-01 | None | Orectogyrus sp. |
| BREE01 | 1975-03-01 | 9.1 | Orthocladiinae |
| BREE01 | 1975-03-01 | None | Orthotrichia sp. |
| BREE01 | 1975-03-01 | 0.6 | Ostracoda |
| BREE01 | 1975-03-01 | None | Oxyethira sp. |
| BREE01 | 1975-03-01 | None | Pelecypoda |
| BREE01 | 1975-03-01 | None | Pelecypoda |
| BREE01 | 1975-03-01 | None | Plecoptera |
| BREE01 | 1975-03-01 | None | Pseudocloeon maculosum |
| BREE01 | 1975-03-01 | 27.4 | Simuliidae |
| BREE01 | 1975-03-01 | None | Sympetrum sp. |
| BREE01 | 1975-03-01 | 1.9 | Tanypodinae |
| BREE01 | 1975-03-01 | 0.5 | Tanytarsini |
| BREE01 | 1975-03-01 | None | Trithemis sp. |
| BREE01 | 1975-03-01 | 1.4 | Turbellaria |

**Comment by dimasciput** [comment]
Let's discuss it at the meeting

**Comment by helendallas** [comment]
@dimasciput @timlinux @jeremyshelton 
The table above includes all taxa recorded at the Coetzer 1986 study , whether present or not at BREE01.  Biobase included absence data as well as presence data. Therefore it was really important to use the column PRESENT in the table dbo_BioSiteVisitBioBiotopeTaxon. Only taxa where Present = 1 were present at the site/sampling date.

So where the abundance is blank on Biobase (presence column must = 1 for a taxon to be present) - or where FBIS has NONE - This means the taxon was NOT present at this site on this sampling date. 

Please refer to the original pdf as well and below. If you take Adenophlebia - it was NOT present at BREE01, with no abundance value, thus it should not be included as present in FBIS.

![image](https://user-images.githubusercontent.com/45286876/75009291-00daa700-5483-11ea-82f0-f328f932b97f.png)

This presence field is used for all records

**Comment by dimasciput** [comment]
We couldn't do this manually for every records, so the formula then if present is 0 then don't import the data to our database? Ok I'll remove all the data with Present 0 then.

**Comment by helendallas** [comment]
@dimasciput  - that is correct dimas. Thanks

**Comment by helendallas** [comment]
@dimasciput @timlinux 

It looks like all duplicates have been removed.

One issue I am noting is that not all taxa are returned in FBIS compared to original Biobase. There are different reasons including:

Genus Hydracarina in Biobase - is returned as Panisus michaeli Koenicke, 1896 in FBIS
Wrong GBIF Name being returned 

Where species dont exist in GBIF, then only Genus returned (e.g. Centroptilum excisum and Centroptilum medium) returned as Centroptilum Eaton, 1869

Some missing completed including Phylum Nematoda (it is on GBIF), and SubFamilies in Family Chironomidae: 
Missing   SubFamily | Chironomini
Missing SubFamily | Orthocladiinae
Missing SubFamily | Tanypodinae
Missing SubFamily | Tanytarsini

Spreadsheets attached.
[Bree01 CSV FBIS Download OccurrenceData.xlsx](https://github.com/kartoza/django-bims/files/4249433/Bree01.CSV.FBIS.Download.OccurrenceData.xlsx)
[Coetzer 1986 Bree01 from Biobase.xlsx](https://github.com/kartoza/django-bims/files/4249434/Coetzer.1986.Bree01.from.Biobase.xlsx)


I am almost done with the Invertebrate Taxon Master List - Perhaps these issues will be resolved once this is included.

**Comment by dimasciput** [comment]
@helendallas yes I think so, thanks

**Comment by timlinux** [comment]
See also #1895

**Comment by timlinux** [comment]
@dimasciput has made a script to fetch the higher order taxa from GBIF - he just needs to run it on testing and live.

**Comment by jeremyshelton** [comment]
OK thanks @timlinux & @dimasciput

**Comment by helendallas** [comment]
@dimasciput 
Please confirm if the script has been run to fetch higher order taxa on the live site?  I need to check the Biobase records, but am not sure where to do this? Presumably live site but I dont want to waste my time if the script has not been run using the Invertebrate master list

**Comment by dimasciput** [comment]
Should be fixed by this ticket -> https://github.com/kartoza/django-bims/issues/1935.

**Comment by helendallas** [comment]
@dimasciput These taxa are still not right on testing. e.g.
Genus Hydracarina in Biobase - is returned as Panisus michaeli Koenicke, 1896 in FBIS
Wrong GBIF Name being returned - should rather be Hydrachnidae




https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=27304&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22129%22]&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=27304&orderBy=name&polygon=

Please confirm if the invertebrate taxonomy master list has been ingested on testing. 

![Screenshot_2020-04-06 FBIS Map(1)](https://user-images.githubusercontent.com/45286876/78557233-b170f000-7810-11ea-92a8-d23d64788032.png)

Here is the spreadsheet for updating original Biobase Taxa - might be worth doing again.

[Biobase Taxon Data for Correcting 2020_03_31.xlsx](https://github.com/kartoza/django-bims/files/4438336/Biobase.Taxon.Data.for.Correcting.2020_03_31.xlsx)

**Comment by helendallas** [comment]
To add to this, obviously Hydracarina is one of the SASS Taxa, so for SASS it will remain as Hydracarina

**Comment by helendallas** [comment]
@dimasciput I am going to close this once you respond. 

Once the data have been ingested to the live site with as many taxonomic issues corrected as possible. I will then go through the taxa on the admin page and correct spelling and add parents to taxa like those below that have missing parents.
 
![Screenshot_2020-04-16 Select Taxonomy to change Django site admin](https://user-images.githubusercontent.com/45286876/79458221-ce1bdd80-7ff1-11ea-8e40-741f872ffa86.png)

I think this is the reason that no subfamilies such as 
Chironomini
Orthocladiinae
Tanypodinae
Tanytarsini

Are not returned for the H1BAKO-00001 (BREE01) site as examined in this ticket.

Please just confirm that I can edit these. What happens if in editing I create duplicate records.
For e.g. I changed Hydropsychidae pupae to Hydropsychidae.....
![Screenshot_2020-04-16 Select Taxonomy to change Django site admin(1)](https://user-images.githubusercontent.com/45286876/79458262-db38cc80-7ff1-11ea-9d7d-412845655777.png)

Do I get an error message if I try and delete a taxon which has data associated with it?  What is the best way to clean up the taxonomy after the final import to the live site

**Comment by helendallas** [comment]
@dimasciput 
I am still concerned that the taxonomy is not all correct for the data imported from Biobase. For example - Searching on Hydracarina

https://freshwaterbiodiversity.org/map/#search/Hydracarina/taxon=&search=Hydracarina&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

![Screenshot_2020-06-12 FBIS Map](https://user-images.githubusercontent.com/45286876/84491223-7d98c780-aca4-11ea-9be6-b076c8b63297.png)

There is no Panisus michaeli Koenike, 1896 in the Biobase data from the legacy dataset (I have checked) , and yet it is listed as such in any of these metadata studies in the table. I checked and they are all Hydracarina.

https://freshwaterbiodiversity.org/map/#species-detail/taxon=1368&search=Hydracarina&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

I have not checked others as it would take an incredible amount of time. This si a long standing issue.....What do you suggest?

**Comment by dimasciput** [comment]
Hi @helendallas I think this is just search issue, I'll investigate it more later

**Comment by dimasciput** [comment]
@helendallas I just found the issue, should be a quick fix. I'll fix it Monday ok?

**Comment by helendallas** [comment]
@dimasciput That's fine thanks

**Comment by dimasciput** [comment]
@helendallas fixed, please try again

**Comment by helendallas** [comment]
@dimasciput Thanks I checked for the one taxon and looks ok. Closing ticket
