### ISSUE TITLE
Taxon CSV needs fixing

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2194]
The CSV for downloading taxon data returns a lot of unnecessary columns and is missing other important ones.

![image](https://user-images.githubusercontent.com/45286876/86350065-6a08cd00-bc62-11ea-8c73-81bf032afc27.png)

https://freshwaterbiodiversity.org/map/#species-detail/taxon=1921&search=Lestagella%20penicillata&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

Ideally it should resemble the other CSV files #2040 

This is the current CSV

[Lestagella penicillata Taxon CSV.xlsx](https://github.com/kartoza/django-bims/files/4863758/Lestagella.penicillata.Taxon.CSV.xlsx)

@jeremyshelton I thought this had been checked and fixed in an earlier version, but I cant remember or find the ticket

**Comment by jeremyshelton** [comment]
@helendallas agreed. 
I am sure we fixed this issue previously, but can't remember what ticket it was...

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas maybe put this on RBIS project (because they will also need it), then I can start working on it next week.

**Comment by helendallas** [comment]
@dimasciput Is this fixed on testing - assume not yet rolled out of FBIS live as not fixed here.

**Comment by helendallas** [comment]
@dimasciput  For RBIS - needs removal of FBIS Site Code - maybe just keep as Site Code, and then all the geocontext data needs to be from RBIS , not FBIS

Highlighted in bold


UUID | Original river name | River name | Original site code | **Fbis** site code | Site description | Refined geomorphological zone | Latitude | Longitude | Sampling date | Kingdom | Phylum | Class | Order | Family | Genus | Species | Taxon | Taxon rank | Sampling method | Sampling effort measure | Sampling effort value | Abundance measure | Abundance value | Broad biotope | Specific biotope | Substratum | Origin | Endemism | Conservation status | Collector/owner | Collector/owner institute | Analyst | Analyst institute | Authors | Year | Source | Reference category | Title | Doi/url | **Geomorphological zone | Primary catchment | Secondary catchment | Tertiary catchment | Quaternary catchment | Water management area | Sub water management area | River management unit | Sa ecoregion level 1 | Sa ecoregion level 2 | Freshwater ecoregion | Province** | Notes

**Comment by timlinux** [comment]
Also please use the download request workflow as we do for occurrence downloader.

**Comment by helendallas** [comment]
Closing ticket as all context columns added to csv although order is wrong. Fine for now.
