### ISSUE TITLE
Please assign correct Collector/Owner to data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2380]
At the moment we are getting some data assigned to 
FBIS , Justine Ewart-Smith
Kartoza_Admin , Helen Dallas

When it should just be Justine Ewart-Smith or Helen Dallas

![image](https://user-images.githubusercontent.com/45286876/99044172-025f7880-2598-11eb-8640-a868a618668b.png)

![image](https://user-images.githubusercontent.com/45286876/99044190-09868680-2598-11eb-9de5-cd0780ad7330.png)

**Comment by dimasciput** [comment]
@helendallas they are the uploader of the data, I can fix it in 1 hour.

**Comment by dimasciput** [comment]
@helendallas should be fixed now

**Comment by helendallas** [comment]
@dimasciput There is still an issue where the person who captured the data (Janette Lumley) did not assign the correct owner when adding the data. I cnaan go and edit this, but she is still listed as the Collector: which should also be Justine Ewart-Smith and which I am unable to edit.  See shots below - you need to add Collector to the edit screen.
https://freshwaterbiodiversity.org/site-visit/detail/12423/

![image](https://user-images.githubusercontent.com/45286876/101134433-06b90780-3613-11eb-8af2-255c94f14069.png)

![image](https://user-images.githubusercontent.com/45286876/101134340-e2f5c180-3612-11eb-8b33-13028d6926d8.png)

**Comment by dimasciput** [comment]
Hi @helendallas you should be able to edit the collector now

**Comment by helendallas** [comment]
@dimasciput Thanks.

Is it possible to add an Update button next to Owner and Collector, to avoid going through all the pages of the site edit. And then once updated to open again at the site visit that you were on.

If this is a mission, then leave and I will work around. Thought I would ask?

**Comment by helendallas** [comment]
Some now blank with no owner
![image](https://user-images.githubusercontent.com/45286876/104415490-c8e8c080-557a-11eb-8f17-e6bb33e1dcff.png)

https://freshwaterbiodiversity.org/site-visit/detail/14750/

**Comment by helendallas** [comment]
Ignore. someone must of added this in my name. No data

Closing ticket looks ok
