### ISSUE TITLE
Algal master list download as CSV

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2381]
Algal Master list downloading does not provide the Division or Growth Form as in the algal master list, and endemism is blank.

Taxon rank | Kingdom | Phylum | Class | Order | Genus | Species | Taxon | Scientific name and authority | Common name | Origin | Endemism | Conservation status
GENUS | Chromista | Ochrophyta | Bacillariophyceae | Achnanthales | Achnanthes | Achnanthes | Achnanthes Bory, 1822 | - | unknown | - | NE
SPECIES | Chromista | Ochrophyta | Bacillariophyceae | Achnanthales | Achnanthes | Achnanthes abundans | Achnanthes abundans | Psammothidium abundans (Manguin) Bukht. & Round | - | unknown | - | NE

**Comment by dimasciput** [comment]
@helendallas I will need 2-3 hours to implement this.

**Comment by helendallas** [comment]
The algal master list CVS needs to be the same as the Master list upload:

CSV: https://freshwaterbiodiversity.org/taxa-management/?&selected=22

Master list uploaded:
[Algal Master File For FBISV4 2020_11_06 Revised in new template.xlsx](https://github.com/kartoza/django-bims/files/6318945/Algal.Master.File.For.FBISV4.2020_11_06.Revised.in.new.template.xlsx)

**Comment by helendallas** [comment]
**Specifically:**

- Family is missing
- Division is missing
- Growth form is missing

**Comment by helendallas** [comment]
See also #2645 

Algal Taxon Master list #2645

**Comment by dimasciput** [comment]
@helendallas please try it again, I just deployed the fix

**Comment by helendallas** [comment]
@dimasciput Looking good so far. Duplicates still present though.

Few issues: Please shift **Family** before **Genus**

And this one has the wrong Kingdom | Phylum -  should be **Chromista | Ochrophyta**

Genus | **Planta | Bacillariophyta** | Bacillariophyceae | Cymbellales | Cymbopleura | Cymbellaceae | &nbsp; | Cymbopleura | Cymbopleura (K.Krammer)   K.Krammer, 1999

Also so others:
Taxon rank | Kingdom | Phylum | Class | Order | Genus | Family | Species | Taxon
Genus | Animalia | Euglenozoa | Euglenoidea | Euglenida | Euglena | Euglenaceae | &nbsp; | Euglena
Genus | Animalia | Euglenozoa | Euglenoidea | Euglenida | Phacus | Phacaceae | &nbsp; | Phacus

Let me check tomorrow further. I suspect some changes might have been made to the taxonomic master list during the reuploading that has resulted in duplicates.

**Comment by helendallas** [comment]
How is it best to deal with these. Correct in Taxon Management edit, then delete duplicate taxon with no records?

**Comment by helendallas** [comment]
@dimasciput I am happy to manually fix the algal taxon master list. Please confirm that this is the correct process:
1. Search for duplicate taxa using the csv file.
2. Correct details of the duplicate taxon that has associated records.
3. Delete the duplicate taxon that does no have associated records.

Once you confirm this is correct I will work through the data, thanks

**Comment by dimasciput** [comment]
@helendallas you can merge taxa in the admin page, https://freshwaterbiodiversity.org/admin/bims/taxonomy/

1. Click the correct taxonomy to open the detail page, check the verified and save
2. Check all the taxa you want to merge, then select "Merge taxa" in the dropdown at the bottom, and click "Go"
![image](https://user-images.githubusercontent.com/1979569/122163457-700db300-ce9f-11eb-8b4a-7985200ed148.png)

**Comment by helendallas** [comment]
@dimasciput okay great, that's what I have done before. Thanks
