### ISSUE TITLE
Critical Biodiversity Areas (CBA) National filters not all working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2399]
The following CBA National filters are not working:

### National Critical Biodiversity:

- Eastern Cape
- Western Cape

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,national_cba_layer,Eastern%20Cape%20Biodiversity%20Conservation%20Plan,%202017%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

![image](https://user-images.githubusercontent.com/45286876/100202291-cc13e880-2f09-11eb-9762-d444a60dbeb1.png)

Also one blank:
![image](https://user-images.githubusercontent.com/45286876/100202413-f2d21f00-2f09-11eb-9971-bb644623576c.png)

Same for protected areas; blank
![image](https://user-images.githubusercontent.com/45286876/100202494-0da49380-2f0a-11eb-97fc-c4161362d23f.png)

**Comment by helendallas** [comment]
From issues #2052

**Comment by dimasciput** [comment]
@NyakudyaA can you help me with this one, can you remove comma from these two values : 
![image](https://user-images.githubusercontent.com/1979569/101119136-4258cf00-361d-11eb-95e8-6c28bd924224.png)

It's in national_cba_layer, thanks

**Comment by NyakudyaA** [comment]
@dimasciput I have fixed this in the DB
![area](https://user-images.githubusercontent.com/2510900/106257673-89ca9880-6225-11eb-82d9-014525c764be.png)

But I think you need to check your filters as some of them i.e Eastern Cape and Westercape look like 

https://freshwaterbiodiversity.org/bims_proxy/https://maps.kartoza.com/geoserver/wfs?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=cba_national_mview&TILED=true&STYLES=red_outline&CQL_FILTER=name in ('Eastern Cape Biodiversity Conservation Plan')&WIDTH=256&HEIGHT=256&CRS=EPSG:3857&BBOX=626172.1357121654,-4383204.9499851465,1252344.2714243294,-3757032.8142729825

**Comment by dimasciput** [comment]
ok thanks @NyakudyaA

**Comment by dimasciput** [comment]
This is resolved, please check @jeremyshelton

**Comment by jeremyshelton** [comment]
@dimasciput - I have tested on both live and testing, but there still seem to be some issues:

1. Eastern Cape filter still not working (seems to be giving data from all provinces)
2. Western Cape filter does not present
3.  I think 'plan' should say 'Area' in the labels

<img width="1279" alt="Screenshot 2021-02-04 at 09 17 36" src="https://user-images.githubusercontent.com/44292029/106858471-65116d80-66ca-11eb-85f2-bc5a329aa264.png">

**Comment by dimasciput** [comment]
@jeremyshelton please test CBA National not provincial

**Comment by jeremyshelton** [comment]
@dimasciput OK
- Looks like Eastern Cape is now working 
- Western Cape is showing the correct selection, but not filtering correctly

<img width="1260" alt="Screenshot 2021-02-04 at 09 26 45" src="https://user-images.githubusercontent.com/44292029/106859208-5c6d6700-66cb-11eb-8adc-0829b9b6bc56.png">

**Comment by dimasciput** [comment]
@jeremyshelton try again now, should be ok

**Comment by jeremyshelton** [comment]
@dimasciput 
Looks good.
Thanks
