### ISSUE TITLE
Ecological category filter not working

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2443]
@dimasciput @helendallas 
The filter for SASS data ecological categories is not working correctly. If I query data from the natural category, the search returns data from multiple categories.

<img width="282" alt="Screenshot 2020-12-08 at 06 07 04" src="https://user-images.githubusercontent.com/44292029/101438819-d8417200-391b-11eb-92e0-b099e9ab7251.png">

**Comment by dimasciput** [comment]
@jeremyshelton it's not a bug, if you open the multi sass dashboard it will returns all SASS data for all the sites. 
https://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22A%22]&rank=&siteIdOpen=11056&orderBy=name&polygon=

**Comment by dimasciput** [comment]
@jeremyshelton but if you open the single SASS dashboard, it will only show you the filtered SASS data

https://freshwaterbiodiversity.org/sass/dashboard/11056/?taxon=&search=&siteId=11056&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22A%22]&rank=&siteIdOpen=11056&orderBy=name&polygon=

**Comment by jeremyshelton** [comment]
@dimasciput OK, but should the filter not apply to all data in the query?
If I select the category Natural (N) and Western Cape Province, then I would expect it to return all the sass assessments that resulted in Natural for the province, or am I missing something?
@helendallas

**Comment by timlinux** [comment]
@dimasciput as discussed with FRC today can you please update the multi-site dashboard to honour the filters that are in place. Single site dash can be left as is.

**Comment by dimasciput** [comment]
@jeremyshelton Hi jeremy, can you test it again, it should honours the filters now. 

![image](https://user-images.githubusercontent.com/1979569/108816781-622edc00-75e9-11eb-8790-9c228e252b94.png)

The grey ones are because we couldn't calculate the ecological condition from the front end due to there are a lot of ecoregion combination.

**Comment by helendallas** [comment]
@dimasciput 
Mostly working but odd strange one coming through:
![image](https://user-images.githubusercontent.com/45286876/109129811-b6f16480-7759-11eb-8cce-0c85343b7877.png)

But when I drill down to the site is is red
https://freshwaterbiodiversity.org/sass/dashboard/11776/?taxon=&search=&siteId=11776&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,eco_region_1,23%20WESTERN%20FOLDED%20MOUNTAINS%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22D%22]&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by helendallas** [comment]
See again this link:
https://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,eco_region_1,23%20WESTERN%20FOLDED%20MOUNTAINS%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22D%22]&rank=&siteIdOpen=&orderBy=name&polygon=

Shows orange for multi-Site but red for single site

**Comment by dimasciput** [comment]
Thanks @helendallas , I'll working on it tomorrow. Can I deploy new fixes to live site tomorrow?

**Comment by helendallas** [comment]
Sure thanks @dimasciput

**Comment by helendallas** [comment]
@dimasciput Still not working 100%, see example below: filtered on 

See example: B2WILG-KRANS is red here:
https://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,sa_provinces,Gauteng%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=[%22E%22]&rank=&siteIdOpen=&orderBy=name&polygon=

But
Single site is an E/F:
https://freshwaterbiodiversity.org/sass/dashboard/9499/?taxon=&search=&siteId=9499&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,sa_provinces,Gauteng%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=[%22E%22]&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by helendallas** [comment]
@dimasciput This still needs checking please

**Comment by dimasciput** [comment]
@helendallas I have fixed it, can you check it again please?

**Comment by helendallas** [comment]
Still an issue, see E1TEER-AWEIR

https://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,primary_catchment_area,Region%20E%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22D%22]&rank=&siteIdOpen=&orderBy=-name&polygon=


https://freshwaterbiodiversity.org/sass/dashboard/11776/?taxon=&search=&siteId=11776&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,primary_catchment_area,Region%20E%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22D%22]&rank=&siteIdOpen=&orderBy=-name&polygon=

**Comment by dimasciput** [comment]
@helendallas can you check it again?

**Comment by helendallas** [comment]
@dimasciput Sorry still seems to be problematic:

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,eco_region_1,19%20SOUTHERN%20FOLDED%20MOUNTAINS%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22A%22]&rank=&siteIdOpen=&orderBy=name&polygon=

![image](https://user-images.githubusercontent.com/45286876/118937622-035dd200-b94e-11eb-8da8-651233eedc0c.png)

https://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,eco_region_1,19%20SOUTHERN%20FOLDED%20MOUNTAINS%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22A%22]&rank=&siteIdOpen=&orderBy=name&polygon=

https://freshwaterbiodiversity.org/sass/dashboard/10220/?taxon=&search=&siteId=10220&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,eco_region_1,19%20SOUTHERN%20FOLDED%20MOUNTAINS%22,%22value,eco_region_1,20%20SOUTH%20EASTERN%20COASTAL%20BELT%22]&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=[%22A%22]&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by dimasciput** [comment]
Hi @helendallas this is actually an issue with the ecological data not being updated for those sites, you can fix it manually by triggering the update script in the background ( I can show you how, but it might be little bit tedious ), or I can create a script later to fix all of the sites with the same problem.

**Comment by helendallas** [comment]
Would we need to query each category per region and then run the script?

I could get one of our data people to assist if its not to complex......

How easy is it to write a script? Might be better?

**Comment by dimasciput** [comment]
@helendallas 
I will create the script later, however I will show you how to update it manually.

- Go to single site SASS dashboard with the error data
https://freshwaterbiodiversity.org/sass/dashboard/10220/?taxon=&search=&siteId=10220&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=%5B%22value,eco_region_1,19%20SOUTHERN%20FOLDED%20MOUNTAINS%22,%22value,eco_region_1,20%20SOUTH%20EASTERN%20COASTAL%20BELT%22%5D&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22%5D&abioticData=&ecologicalCategory=%5B%22A%22%5D&rank=&siteIdOpen=&orderBy=name&polygon=

- Click the SASS records 
![image](https://user-images.githubusercontent.com/1979569/118940938-6dd93700-b97b-11eb-89c0-c1490c6889a5.png)

- Go to edit mode but don't change anything

- Click next, after the first form/page you don't need to click next again.

Done, it will update the ecological data in the background.

**Comment by helendallas** [comment]
@dimasciput We have manually fixed all of these. There were some that didn't want to change colour, but the minority. So I am closing the ticket.
