### ISSUE TITLE
CSV Download for Invertebates in Taxon Management does not work

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2497]
I cannot download the csv of taxa - "Download as CSV" does not return anything, while for fish and algae it does.

![image](https://user-images.githubusercontent.com/45286876/105847980-091e5900-5fe7-11eb-8e25-42d5160ee6a4.png)

It may be because of the number of records.

**Comment by dimasciput** [comment]
@helendallas it worked, but it did take a while because there were lots of records. Maybe I need to show some kind of loading animation on the button.

**Comment by helendallas** [comment]
@dimasciput I havent received anything, where does it go to? For fish and algae it pops up as follows:

![image](https://user-images.githubusercontent.com/45286876/105977602-3a0b9600-609a-11eb-86c6-1d5a0c88a37d.png)


But since inverts takes so long, it disappears. Maybe these should also be changed to being sent by email?

**Comment by helendallas** [comment]
@dimasciput Please can you check. I need to retrieve existing Invertebrate Master List to double check against my excel file. Thanks

**Comment by dimasciput** [comment]
@helendallas this is fixed and deployed to live.

**Comment by helendallas** [comment]
@dimasciput error

![image](https://user-images.githubusercontent.com/45286876/126618817-fe59ab1f-32e7-4e94-96ad-399581d7e933.png)

**Comment by helendallas** [comment]
@dimasciput Please check this. It goes to 
file:///C:/Users/Helen%20Dallas/AppData/Local/Temp/Taxa_list.csv.htm

And I can still not access the file

**Comment by helendallas** [comment]
@dimasciput still not working....downloaded csv file has the following in it:

<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

**Comment by dimasciput** [comment]
@helendallas please test this, now the process will be similar to other downloads.

**Comment by helendallas** [comment]
@dimasciput Thanks that is better, all work fine except algae csv is only downloading 374 species instead of 444 taxa.
Please can you check what is happening here.

**Comment by helendallas** [comment]
I will investigate this further, to try and understand the issue., closing ticket
