### ISSUE TITLE
Taxon Management csv files

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2557]
Please change indigenous to native and alien to non-native in the downloaded csv file.

![image](https://user-images.githubusercontent.com/45286876/111619234-fe659080-87ed-11eb-8a15-25d51adb71f6.png)

Also common names are not coming through correctly.

Taxon | Scientific name and authority | Common name
-- | -- | --
Actinopterygii | Actinopterygii | -
Amatolacypris trevelyani | Amatolacypris trevelyani GÃ¼nther, 1877 | -
Ambassis natalensis | Ambassis natalensis Gilchrist & Thompson, 1908 | Slender glassy
Amphilius natalensis | Amphilius natalensis Boulenger, 1917 | -
Amphilius uranoscopus | Amphilius uranoscopus (Pfeffer, 1889) | Stargazer mountain catfish
Anguilla bengalensis | Anguilla bengalensis (Gray, 1831) | -
Anguilla bicolor | Anguilla bicolor McClelland, 1844 | Shortfin eel
Anguilla labiata | Anguilla labiata (Peters, 1852) | -
Anguilla marmorata | Anguilla marmorata Quoy & Gaimard, 1824 | -
Anguilla mossambica | Anguilla mossambica (Peters, 1852) | -
Astatotilapia calliptera | Astatotilapia calliptera (GÃ¼nther, 1894) | -
Austroglanis barnardi | Austroglanis barnardi (Skelton, 1981) | Barnard's rock catfish
Austroglanis gilli | Austroglanis gilli (Barnard, 1943) | Clanwilliam rock catfish
Austroglanis sclateri | Austroglanis sclateri (Boulenger, 1901) | Barnard's rock catfish
Brycinus imberi | Brycinus imberi (Peters, 1852) | Imberi

**Comment by dimasciput** [comment]
This should be fixed now, @helendallas

**Comment by helendallas** [comment]
@dimasciput For all please move Family before Genus, thanks

Also still not workign for invertebrates due to the size. I get error message:
file:///C:/Users/Helen%20Dallas/AppData/Local/Temp/Taxa_list.csv.htm

**Comment by helendallas** [comment]
@dimasciput Column order still needs fixing  -For all please move Family before Genus, 

Once done I can close the ticket

**Comment by dimasciput** [comment]
Fixed on live @helendallas

**Comment by helendallas** [comment]
Thanks checked fine now, closing ticket
