### ISSUE TITLE
Please check that only OdonataMap data are linked to Odonata Adults module

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2566]
When I downloaded the csv of all OdonataMap records, I am still getting other invertebrate data.

![image](https://user-images.githubusercontent.com/45286876/112115902-62a79c00-8bc2-11eb-82a2-0bdcc16b322d.png)

Here is an excel file showing filtered records (191 - highlighted), using sampling method (excluding Human Observation and Photographic record, which are linked to Odonate adult data only.

[All Odonates downloaded form FBIS 2021_03_23 Ex Odonata adult data.xlsx](https://github.com/kartoza/django-bims/files/6188062/All.Odonates.downloaded.form.FBIS.2021_03_23.Ex.Odonata.adult.data.xlsx)

These should not be returned in the csv file for the Odonate Adults module.

Please can you check.

**Comment by helendallas** [comment]
So all odonata adults, metadata shows only database, but when one downloads the csv files, other records are included.

![image](https://user-images.githubusercontent.com/45286876/118941866-779a7480-b952-11eb-924e-0d99a7950e13.png)

![image](https://user-images.githubusercontent.com/45286876/118941928-8bde7180-b952-11eb-9d59-a750a9750554.png)


https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=34&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

When I downloaded the CSV file of all this data, most records were correct but there were many - highlighted in yellow - that had been reassigned to Virtual Museum database, instead of the correct source.

@dimasciput Please can you investigate what has happened and correct the data please.

Here is the excel file: It is to large to include, so will send vi wetransfer.

**OdonataMap data extracted from FBIS with incorrect data.xlsx**

**Comment by dimasciput** [comment]
Hi @helendallas , I'm sorry I forgot to download the file and now the link has expired. Could you reshare it again?

**Comment by helendallas** [comment]
Hi @dimasciput  Link still active above, shows highlighted taxa that should not be included (see link at top of the ticket)

All Odonates downloaded form FBIS 2021_03_23 Ex Odonata adult data.xlsx

**Comment by dimasciput** [comment]
@helendallas but that's the old issue, I think I already fixed it. Can you try it again maybe?

**Comment by helendallas** [comment]
@dimasciput Yes an old issue but I tested it again and it was still a problem. I will run an extraction of all Odonata data gain although it takes a long time.

**Comment by helendallas** [comment]
@dimasciput 

So I have just extracted all data from the Odonate adult module. The attached excel file highlights all the records that are definately not OdonataMap data but which belong to specific studies uploaded to FBIS. They have been incorrectly assigned to OdonataMap as the source. I have no idea how this has happened. 

![image](https://user-images.githubusercontent.com/45286876/128027192-bd6b9f3f-0343-43b1-b457-21d169e4466e.png)

Also some data are Collector/Owner as "Administrator Administrator" - not sure why. I have no idea what these data are?

Here is the file sorted on sampling method. All OdonataMap data are either Human observation or Photographic record.  I will send via Wetransfer to you as it is to large to attached to github

Please can you investigate what has happened and then the data need to be fixed.

**Comment by dimasciput** [comment]
> Also some data are Collector/Owner as "Administrator Administrator" - not sure why. I have no idea what these data are?

That means they don't have owner/collector in the source, the system will set the owner to admin.

> Please can you investigate what has happened and then the data need to be fixed.

Ok, will check it today.

**Comment by dimasciput** [comment]
@helendallas this is fixable, the cause of this problem is the script I use to update all odonate reference data to the museum also updates other odonate data that doesn't belong to the adult odanate group. So sorry, it was my fault.

**Comment by dimasciput** [comment]
@helendallas this should be fixed now

**Comment by helendallas** [comment]
Thanks all sorted now.
