### ISSUE TITLE
Multiple databases being created when occurrence data uploaded

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2705]
We had this issue previously. Why when occurrence data is uploaded and assigned the same Source, in this case database, the Source Reference list it multiple times. It should be one database if it has the same name

![image](https://user-images.githubusercontent.com/45286876/127998519-32a0d4c9-af99-4ab5-a908-f9169f8c3670.png)

This was recently uploaded by @aneriswanepoel

**Comment by dimasciput** [comment]
@helendallas this is because they have different years, so it will create a new database record.

**Comment by dimasciput** [comment]
@helendallas do you want to remove year data from database source?

**Comment by helendallas** [comment]
@dimasciput Yes please can you remove the date. Aneri must of misunderstood. Thanks

**Comment by aneriswanepoel** [comment]
@helendallas I see there is also some other data that was uploaded where FBIS automatically added the year to the source. @dimasciput do you need a list of these data or is it a setting that you can change and will apply to all sources?

**Comment by helendallas** [comment]
@dimasciput Progress on this? I don't mind manually fixing in Source references, but don't want it to keep happening eveytime we upload new occurrence data.

It should just be the **Source** column that is imported for **Database**, and **Unpublished data** - not the year, so that multiple database or sets of data are not created.

Can I manually fix for Unpublished data? and Databases? Or is it something easier for you to do in the backend?

**Comment by helendallas** [comment]
@dimasciput I have manually combined the Unpublished data, but this does not work for databases.

**Comment by dimasciput** [comment]
Hi @helendallas , yes for databases I need to do it from backend. I also need to update the uploader script to not add the year to database.

**Comment by dimasciput** [comment]
@helendallas can you for now remove the year from nepid database, I will merge it from backend.

**Comment by helendallas** [comment]
Okay thanks Dimas, please let me know when this is done so that we can continue with our uploading, without creating multiple databases or unpublished datasets.

**Comment by helendallas** [comment]
Okay, I will do now, there are some others, I will capture in ticket . Thanks

**Comment by helendallas** [comment]
@dimasciput I am done, the following databases need to be merged, as there are multiple versions of each:

- Nepid fish database
- Rivers Database 2015
- South African National Parks Fish Database
- Mpumalanga Tourism and Parks Agency
- Limpopo Department of Environmental Affairs, Fish Database
- Ecosun Fish database
- Clean Stream Biological Services database
- FRC monitoring database

**Comment by helendallas** [comment]
@dimasciput A thought in terms of future maintenance - how difficult would it be to develop the functionality to allow an admin person to merge database in the same way as it is done for Unpublished data?

**Comment by helendallas** [comment]
@dimasciput Is this fixed yet. We are needing to upload new data needed for species distribution modeling which is on a tight timeframe, but if we upload it will create multiple database again if date is still included.

Please revert soonest

**Comment by dimasciput** [comment]
Hi @helendallas you can go ahead uploading the data now, I have merged the database and also added the fix in the uploader script.

**Comment by helendallas** [comment]
@dimasciput Still not sure this is working correctly, for either database or unpublished data. see example below:

![image](https://user-images.githubusercontent.com/45286876/134163022-abb00b69-ea24-4e36-9ba9-05204f597afd.png)

![image](https://user-images.githubusercontent.com/45286876/134163078-9ddff77f-6c2c-47d5-954d-39a7a32e7aea.png)

And we have manually had to combine unpublished datasets as they were all given different dates

**Comment by aneriswanepoel** [comment]
> @aneriswanepoel please can you test this and feed back on if it's working on live site? Thanks

I have tried to upload dummy data to Testing to test this but the upload is not working (see #2780) so waiting for Dimas to sort that out
