### ISSUE TITLE
Removal of download request button duplicates

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#2897]
Hi @dimasciput 

Can you also remove one button for the download request in the final site

![image](https://user-images.githubusercontent.com/64961274/149352481-7d28d785-0383-46ce-9b1d-e7fc52335aa8.png)

**Comment by dimasciput** [comment]
@mmindje this is fixed in testing

**Comment by mmindje** [comment]
Thank you- saw this issue is still unfixed in the final site.
Hope you also remember to fix it.

Thank you Dimas

**Comment by mmindje** [comment]
> @mmindje this is fixed in testing

Hi @dimasciput Can you also remove the download button from the final site?
Thank you

**Comment by helendallas** [comment]
This has been fixed, closing ticket

![image](https://user-images.githubusercontent.com/45286876/158594564-aeceab4d-0f61-4c53-a68d-fd8c815901d0.png)
