### ISSUE TITLE
Master list CVS downloads

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3164]
Please can you revise the download of the taxa csv files to match the Master List upload file.

Slightly revised to include **Taxonomic status** column (This relates to the GBIF taxonomic status) - when a master list is created the user will populate this column, but ideally it should be drawn from GBIF.

![image](https://user-images.githubusercontent.com/45286876/184881192-f59645b4-6d67-4fe8-89ff-53a4efa4f3c1.png)

[FBIS Master List Template final for FBIS Generic 2022_08_01.xlsx](https://github.com/kartoza/django-bims/files/9350971/FBIS.Master.List.Template.final.for.FBIS.Generic.2022_08_01.xlsx)

The download CSV must include all of these colums please especially SubSpecies whihc is presently missing

Also Algal Master list csv must also include Division and Growth form

**Comment by helendallas** [comment]
PLease see revised suggestion below:

We only have one upload Taxonomic data upload template that includes extra columns for algae. 


Here is it

[FBIS Master List Template final for FBIS Generic 2022_08_16.xlsx](https://github.com/kartoza/django-bims/files/9351270/FBIS.Master.List.Template.final.for.FBIS.Generic.2022_08_16.xlsx)

**Comment by dimasciput** [comment]
This is fixed on testing.

**Comment by helendallas** [comment]
@dimasciput I am still getting the old file not the new one

![image](https://user-images.githubusercontent.com/45286876/205285845-1d395de5-da21-4397-b0a9-b28ad316a0e1.png)

**Comment by helendallas** [comment]
Working now after I updated the upload again, closing ticket
