### ISSUE TITLE
Fix filter for Conservation Status global

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3275]
When the national conservation status categories were added, an error arose in the filter

![image](https://user-images.githubusercontent.com/45286876/205284626-a14c7959-d527-4a82-9646-3beff7e902a5.png)

It may be worth also including a filter for Conservation Status National?

Or better?

Making conservation status the drawer, which opens to allow the user to select Global or National -  either is fine, do whatever is simpler and makes sense

@jeremyshelton your thoughts?

**Comment by dimasciput** [comment]
Fixed in testing

**Comment by helendallas** [comment]
@dimasciput This is not fixed correctly as per the ticket. 

As mentioned above, we need to be able to filter on global and national. At the moment it says global but then some categories are national.

![image](https://user-images.githubusercontent.com/45286876/218447369-b447d00a-9c4e-404a-a055-379a3dd2edfd.png)
It would be better to have two separate ones:

Conservation status global
Conservation status national

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput 
Agreed. The structure should be as follows:

<img width="294" alt="Screenshot 2023-02-16 at 07 15 08" src="https://user-images.githubusercontent.com/44292029/219274848-79b29061-673f-4703-9bba-a8def535630c.png">

[Cons status categories.xlsx](https://github.com/kartoza/django-bims/files/10752405/Cons.status.categories.xlsx)

**Comment by jeremyshelton** [comment]
@dimasciput it looks to me that there are several categories missing from conservation status national? Also the secondary text (green highlights) is not needed in these labels.

<img width="279" alt="Screenshot 2023-03-21 at 06 36 35" src="https://user-images.githubusercontent.com/44292029/226518359-b89bcece-af71-4d8d-ae26-92cfea3433f4.png">

**Comment by helendallas** [comment]
@jeremyshelton The way the filters are are a bit confusing. Conservation status national has the same categories as global, but with extra. A user will either want to filter on global status or national status.

@dimasciput 
The filter should rather give both options with the full list for each as per you xls table (without the abbreviations), not the way it is at the moment:
![image](https://user-images.githubusercontent.com/45286876/226866389-0301706f-e210-4f53-b209-a51eb61eedf2.png)

**Comment by dimasciput** [comment]
@jeremyshelton this has been fixed in production

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - looks good
