### ISSUE TITLE
Print map not working

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3752]
The print map functionality is not working no matter what the basempa is. Error message received.

I tried all the baseman's, none print.

A user was asking which is why I checked.

![Screenshot 2024-03-13 at 10 29 51](https://github.com/kartoza/django-bims/assets/45286876/fcdc466b-1c95-4bd4-ba20-6479024f35b8)

**Comment by dimasciput** [comment]
@helendallas fixed in production

**Comment by helendallas** [comment]
@dimasciput Still an issue, spinning when I select topography. Suggest adding popup?

**Comment by dimasciput** [comment]
@helendallas, this has been fixed in testing. It might take longer to download the topography map, but it should work.

**Comment by helendallas** [comment]
Great @dimasciput This is working now. Please deploy to production after training.

**Comment by dimasciput** [comment]
Deployed to production
