### ISSUE TITLE
CSV file downloads has incorrect subspecies/species categories.

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4419]
The CSV file that is downloaded does not always have the correct : 

Genus Species SubSpecies details
 e.g.
here species and subspecies is given in the SubSpecies column

<img width="816" alt="Image" src="https://github.com/user-attachments/assets/c158b705-c106-404c-8ac9-88057914418a" />

**Comment by helendallas** [comment]
@dimasciput This is really urgent as SANparks download the CSV file, then edit it and want to upload again. Nut now they will be uploading the csv that has Species and Subspecies in the Subspecies column as this is what is currently brought down in the csv.

Please respond soonest and indicate if they need to now edit the SubSpecies column to remo\ve the Species part.

**Comment by dimasciput** [comment]
@helendallas no, for now let's keep it this way, I will update in the backend to remove the species from the subspecies. However, we need to standardize the process. Let's discuss that later.

**Comment by helendallas** [comment]
Please can you clarify as this needs to be standardised across all BIMS or it gets very confusing to train.

In FBIS we had subspecies on its now in a separate column: In my mind this is correct and is the way it should be. I am not sure what or when it changed.

![Image](https://github.com/user-attachments/assets/fe367ccb-982d-48ea-b532-d4c3eda407ee)

**Comment by helendallas** [comment]
@dimasciput Have we resolved this. ?

**Comment by dimasciput** [comment]
@helendallas this is fixed

**Comment by helendallas** [comment]
<img width="1202" alt="Image" src="https://github.com/user-attachments/assets/402a4778-40b4-49f3-811a-61fe837349d9" />

Still a problem - this is SANParks

**Comment by helendallas** [comment]
Further to above, it works with accepted names but not synonyms

<img width="1258" alt="Image" src="https://github.com/user-attachments/assets/11a7feca-ec90-4e6f-9fa0-586bc56e1193" />

**Comment by helendallas** [comment]
@dimasciput Anything further on this?

**Comment by helendallas** [comment]
I am going to close this as I think it will be dealt with in the new SANParks phase 2, where there is budget for resolving issues with synonyms and accepted names etc.
