### ISSUE TITLE
Species upload issues

### ISSUE THREAD

**Issue by schmikloi** [kartoza/django-bims#4453]
@dimasciput @helendallas 

In preparation for uploading the first ready-to-go species lists, I tested the upload again and found the following issues:

1) one subspecies was not uploaded; error message: 'NoneType' object has no attribute 'parent'
I did not manage to find what is wrong with this species (even more: at an earlier attempt to upload this file I did not get an error message....)

2) I provided 3 GBIF keys, which seemingly were not considered; instead the species was linked to a totally wrong species (wrong genus name) from GBIF 

3) the synonymised species are displayed wrongly in the detailed view; in the field "Species" there should only be "albopunctatus"

<img width="1015" alt="Image" src="https://github.com/user-attachments/assets/47ed1099-8365-4db3-8f41-ed47c799b309" />

4) the upload of the tags confuses me: for several species it says aquatic AND water-dependant, even though it is not like this in the upload file;
for the last in the list (Gordius albopunctatus) there are even tags that should not exist (Biogeographic reference)

5) for the common names we agreed to only import/display the Englisch ones 🤔? (sorry if I forgot)

Here is the file I worked with
[nematomorpha_upload_v2.xlsx](https://github.com/user-attachments/files/19105609/nematomorpha_upload_v2.xlsx)

**Comment by dimasciput** [comment]
@schmikloi I have checked your csv file, there are some issues with it : 

| On GBIF | GBIF URL                                      | Scientific name and authority | Origin | Endemism | Taxon Rank | Kingdom  | Phylum      | Class      | Order   | Family   | SubFamily | Tribe | SubTribe | Genus  | SubGenus | SpeciesGroup | Species       | SubSpecies     | Author(s)       | Taxonomic Status | Accepted Taxon | Taxonomic References | Taxonomic Comments | ANT | AT | AU | NA | NT | OL | PAC | Biogeographic References | Biogeographic Comments | Aquatic | Water-dependent | Freshwater | Limno-terrestrial | Brackish | Others | Lentic | Lotic | Parasitic | Hosts | Environmental References | Environmental Comments | Common Name                        | Conservation Status | Conservation References | Conservation Comments                     |
|--------|----------------------------------------------|------------------------------|--------|----------|------------|----------|-------------|------------|---------|---------|----------|-------|----------|--------|----------|--------------|---------------|---------------|----------------|----------------|---------------|---------------------|-----------------|-----|----|----|----|----|----|-----|--------------------------|------------------------|---------|----------------|------------|------------------|---------|--------|--------|------|-----------|-------|--------------------------|------------------------|----------------------------------|--------------------|---------------------|-----------------------------------------|
| yes    | [GBIF Link](https://www.gbif.org/species/8343290) |                              |        |          | SubSpecies | Animalia | Nematomorpha | Gordioida  | Gordiida | Gordiidae |          |       |          | Gordius | Gordius  |              | albopunctatus | albopunctatus | Müller, 1926   | accepted       |               | Schmidt-Rhaesa, 2024 |                 |     |    |    |    |  Y  |    |     | Schmidt-Rhaesa, 2024     | little is known about the distribution of the species | Y       | Y              |            |                  |         |        | Y      |      | Y         |       | Schmidt-Rhaesa, 2024     | little is known about the ecology of the species | Weißpunktiertes Wasserkalb (ger) | endangered         | Schmidt-Rhaesa, 2024 | only few individuals left in the world |

Your GBIF URL is for the species, but this is a subspecies. Additionally, you need to upload the species first, then the subspecies. That's why you're getting the parent error.

**Comment by dimasciput** [comment]
Here's the example that should work with the uploader : 

[nematomorpha_upload_v2_fixed.csv](https://github.com/user-attachments/files/19193516/nematomorpha_upload_v2_fixed.csv)

**Comment by schmikloi** [comment]
@dimasciput 

ad 1) I tried with uploading the species first and for one sub species this worked; for the other it did not
ad 2) seems to be solved
ad 3) this is still not correct
ad 4) this is still not correct; in my latest upload test, some of the tags were completely missing
also in my latest attempt: species that were tagged as "synonym" were uploaded as "accepted"
ad 5) common names are not displayed

Should I create separate issues for the remaining 4 issues?

**Comment by dimasciput** [comment]
@schmikloi please try again, this should be fixed

**Comment by schmikloi** [comment]
@dimasciput 

@1) this works now, thanks!

@3) is better, but still not correct for the subspecies

<img width="1618" alt="Image" src="https://github.com/user-attachments/assets/72799d99-d70b-4ff0-a1a6-975479efb286" />

<img width="1481" alt="Image" src="https://github.com/user-attachments/assets/6bfdf962-2ae6-4b1e-a1a4-c4b80181d1d0" />

in the subspecies field there should be another "alpinus"

@4) some tags are wrongly imported; I attach the Excel file I used for upload; I have marked the wrong tags in orange

[nematomorpha_upload_v3.xlsx](https://github.com/user-attachments/files/19366848/nematomorpha_upload_v3.xlsx)

@5) works for English common names

**Comment by dimasciput** [comment]
> @schmikloi works for English common names

Currently we are only showing the english common names, because there will be a lot of common names from gbif. Do you want to show them all?

**Comment by dimasciput** [comment]
>@4) some tags are wrongly imported; I attach the Excel file I used for upload; I have marked the wrong tags in orange

@schmikloi this is because the data previously included these tags. I will update it so that the tags are refreshed based on the CSV.

**Comment by schmikloi** [comment]
> > [@4](https://github.com/4)) some tags are wrongly imported; I attach the Excel file I used for upload; I have marked the wrong tags in orange
> 
> [@schmikloi](https://github.com/schmikloi) this is because the data previously included these tags. I will update it so that the tags are refreshed based on the CSV.

That would be super cool and very useful; I think the tags should completely be overwritten if a new file is uploaded... what do you think @helendallas ?

**Comment by schmikloi** [comment]
> > [@schmikloi](https://github.com/schmikloi) in the subspecies field there should be another "alpinus"
> 
> This is actually a species not subspecies, the subspecies is not added to this group. I will check it

Well the synonym is a species and the accepted taxon is a subspecies... (a bit confusing🙄...)

**Comment by helendallas** [comment]
For @dimasciput For the tags, I implemented this on staging last Friday. It will override existing tags now.  So I will close this ticket now.
