### ISSUE TITLE
Sites not showing on may when no filter is selected

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#4572]
![Image](https://github.com/user-attachments/assets/6bcc8809-b4fc-4b23-a9c3-5b61dbcda056)

**Comment by dimasciput** [comment]
@helendallas this should be fixed

**Comment by helendallas** [comment]
Still not working my side and I cleared the cache and did a hard refresh
